- Gwayeon/Controllers/DetailViewController.swift
- Gwayeon/Controllers/EmptyButtonCollectionViewCell.swift
- Gwayeon/Controllers/FruitListView.swift
- Gwayeon/Controllers/HomeViewController.swift
- Gwayeon/Controllers/MyPageViewController.swift
- Gwayeon/RecommendFarmViewController.swift
> [Feat] Navigation Link 및 코드 정제화

- Gwayeon.xcodeproj/project.pbxproj
- Gwayeon/Globals/Extension/UIView+Extension.swift
#69 
UIView Extension 추가로 addSubview를 간단하게 구현하기
addSubViews(_ ) 사용전 
```swift
[myRecommendationButton, purchaseListButton].forEach { button in
view.addSubview(button)
button.translatesAutoresizingMaskIntoConstraints = false
}
```
addSubviews(_ ) 사용후
```swift
view.addSubviews(myRecommendationButton, purchaseListButton)
```
> [FEAT] addSubviews라는 함수 UIView Extension추가

- Gwayeon.xcodeproj/project.pbxproj
- Gwayeon/Controllers/UsernameSettingViewController.swift
#52
username setting view UI 구현
textfield border style을 underline에서 rectangle로 바꾸었습니당
> [FEAT] username setting view UI 구현

- Gwayeon.xcodeproj/project.pbxproj
- Gwayeon/Controllers/FruitRecommend/FruitSelectViewController.swift
- Gwayeon/Controllers/FruitRecommend/View/FruitSelectCollectionViewCell.swift
#54 
- 변경된 과일 리스트로 구현했습니다.
- 과일 이미지를 하나로 구현할 예정이었으나 과일이미지 추가가 완료돼서 각 이미지를 넣었습니다.
- collectionview와 cell의 layout 확인해주세요
> [Feat] 과일 선택 UI 구현

- Gwayeon.xcodeproj/project.pbxproj
- Gwayeon/Globals/Extension/UIViewController+Extension.swift
- Gwayeon/InputSection.swift
- Gwayeon/RecommendFarmViewController.swift
#81 
- 과일 선택 TextField로 구현되어있던 것 예정된 UI로 변경했습니다.
- #85 에서 과일 선택 뷰와 연결 예정입니다.
- 다른 입력창과 같은 느낌을 주기 위해서 textfield에 interaction을 막아서 구현했습니다.
- textfield의 rightview를 사용해서 아래 화살표를 넣었습니다.
> [Feat] 과일 추천 - 과일 선택 ui 변경

- Gwayeon.xcodeproj/project.pbxproj
- Gwayeon/Controllers/UserProfileCompletionViewController.swift
- Gwayeon/Controllers/UsernameSettingViewController.swift
#93 
username 입력받고 다음 뷰로 username 패스하는 부분입니다.
> [Feat] 프로필 세팅에서 username passing

- Gwayeon.xcodeproj/project.pbxproj
- Gwayeon/FirebaseManagerTestUI/TestViewController.swift
- Gwayeon/Manager/FirebaseManager.swift
- Gwayeon/Models/Fruit.swift
- Gwayeon/Models/Recommend.swift
- Gwayeon/Models/User.swift
- Gwayeon/SceneDelegate.swift
#88 
Relation DB를 구축한 이유는, 각 Document ID를 활용하여 바로 문서를 참조하기 위함인데, pinCode와 userName이라는 field를 통해 Document를 가져오는 불필요한 depth가 추가됐다. 이로인해 관계형 디비의 장점을 살리지 못하였기에 이를 해결하기 위해 구현하였다. 
모델을 보고, 각자 맡은 뷰에서 어떤 ViewModel을 가져야 할 지 생각해보면 좋을 것 같다!
> [Feat] 파이어베이스 기본적인 모델, 다시 만들기

- Gwayeon/InputSection.swift
- Gwayeon/RecommendFarmViewController.swift
#91 
- 기본으로 완료버튼이 disabled되게 했습니다.
- 각 섹션 입력이 끝날 때마다 값 체크를 합니다
- done 버튼을 눌렀을 때 다음 섹션으로 넘어가게 구현했습니다.
- RecommendFarmViewController에서 각 InputSection에 action을 넣어주고 입력 시작할 때, 완료할 때, done 버튼을 눌렀을 때 action을 하도록 했습니다.
- 참고사항의 영상을 확인해주세요
> [Feat] 과일 추천 입력값 체크와 다음 섹션으로 넘기기 구현

- Gwayeon/Controllers/FriendAddViewController.swift
#106 
디버깅 과정에서 잘못된 타이핑을 수정하지 못하고 Merge했습니다!
빠른 approve 부탁드려요!
> [Chore] 오타 수정

- Gwayeon/Controllers/UserProfileCompletionViewController.swift
- Gwayeon/Manager/FirebaseManager.swift
- Gwayeon/SceneDelegate.swift
#108
[Feat] 유저 생성 및 온보딩
- #89 리뷰 반영
- 닐의 테이블과 같은 이름으로 생성
> [Feat] 유저 생성 및 온보딩

- Gwayeon/Controllers/FriendAddViewController.swift
#97 
추가 버튼을 화면에 추가하였습니다
검색 결과가 있을 때만 추가 버튼을 활성화했습니다
isEnabled를 활용하여 button의 disabled state를 변경하는 방식을 사용하였습니다
> [Feat] Friend Add (과연 추가) 화면 추가 버튼 구현

- Gwayeon/FirebaseManagerTestUI/TestViewController.swift
- Gwayeon/Manager/FirebaseManager.swift
#121 
나의 uid, 친구의 uid를 모두 받아서 서로의 friends에 추가한다. 
최대한 빠른 시간안에 approve 부탁드립니다.
> [Feat][긴급] 친구추가 FirebaseManager 구현완료

- Gwayeon/Controllers/UserProfileCompletionViewController.swift
- Gwayeon/Manager/FirebaseManager.swift
#124 
쓸일이 많은 것 같아서, 로그인한 유저 정보를 가져오는 함수를 만들었어요
저는 닐과 달리, async/await로 코드를 작성했어요!
이런 식으로 쓰면 됩니다.!!
```swift
private var user: User?
override func viewDidLoad() {
super.viewDidLoad()
fetchData()
}
private func fetchData() {
Task { [weak self] in
self?.user = await FirebaseManager.shared.getUser()
}
}
```
> [Feat] 로그인된 사용자 정보 가져오기

- Gwayeon/RecommendToFriendViewController.swift
#111 
1. 과연에게 추천하기에서 적은 추천한마디 firestore 연결
2. textview 비어있을 때 버튼 disabled
3. 농장, 과일, friendCount 이전 화면에서 받아오기
이전 화면인 mypage에서 userId, username, fruitId 전달받고 comment를 TextView로 입력받아 sendRecommend()로 firestore와 연결합니다.
> [Feat] 추천 한마디 firestore 연결 

- Gwayeon/RecommendFarmViewController.swift
#109 
- 과일 추천하기에서 완료버튼을 누르면 서버에 정보가 추가되게 연결했습니다.
- sendfruitdata 함수에서 확인하실 수 있습니다.
- fruitcode를 담는 변수가 추가됐습니다. (과일 선택에서 Int로 코드를 받아와 과일 이름 String으로 보여주기 때문)
- 과일 등록을 하고 추천을 추가합니다
- 추후 변경사항은 TODO 확인 부탁드립니다.
위와 같이 입력하고 완료 버튼을 눌렀을 때 아래와 같이 firestore에 들어가는 것 확인했습니다.
> [Feat] 과일 추천하기 - 서버 연결

- Gwayeon/Controllers/FriendAddViewController.swift
- Gwayeon/Controllers/FruitEmptyView.swift
- Gwayeon/Controllers/HomeViewController.swift
- Gwayeon/FriendList/FriendListViewController.swift
#105 
과연 추가 화면 모달 연결 (홈 화면, 과연 리스트 화면과 연결)
모달의 네비게이션 바 생성 (타이틀, 취소 버튼)
모달뷰로 구현하였기 때문에 navigation controller를 쓸 수 없어서
navigationBar 를 따로 생성하여 화면에 추가하는 방식으로 구현했습니다.
홈 화면과 과연 추가 뷰를 연결하기 위해 FruitEmpty View 내에 있던 "과연 찾아보기" label을 HomeView 로 옮기는 작업 수행했습니다.
- FruitEmpty 뷰 내에서 모달 연결을 위한 present 코드를 작동시키는 방법을 못 찾아서 이렇게 구현했는데, 좋은 방법이 있다면 알려주세요!
> [Feat] FriendAdd(과연 추가) 화면 모달 구현

- Gwayeon/RecommendFarmViewController.swift
#130
- 임의로 유저 정보를 넣어놓고 과일 추천을 서버에 보냈던 기존 방식에서 유저 정보를 가져와 추천을 보내는 방식으로 변경했습니다.
- https://github.com/DeveloperAcademy-POSTECH/MC3_Team5_NealAndBori/pull/125 를 참고해서 유저 정보를 가져와 과일 추천을 서버에 보내도록 했습니다.
이번에는 사과 농장으로 확인해봤습니다!
> [Feat] 유저 정보 가져와서 과일 추천하기

- Gwayeon/RecommendToFriendViewController.swift
#132 
임의로 userId와 userName을 넣어놓고 추천한마디를 서버에 보냈던 기존 방식에서 fetchUserData()를 이용해 유저 정보를 가져와 추천한마디를 보내는 방식으로 변경했습니다.
> [Feat] 과연에게 추천한마디 - 유저정보 가져오기 적용

- Gwayeon/Controllers/FriendAddResultCellView.swift
- Gwayeon/Controllers/FriendAddViewController.swift
#121 
과연 추가 버튼 서버 연결 완료
친구 검색 결과 서버 연결 완료
동작되는지 확인했습니다
혹시 놓친 부분이 있다면 알려주세요
테스트 사용자는 '과연추가사용자' 이고, '과연추가친구3'을 새로운 과연으로 추가한 후 파이어베이스에 '과연추가친구3'이 friends에 추가되는 것 확인했습니다.
> [Feat] FriendAdd(과연 추가) 화면 서버 연결

- Gwayeon/Controllers/DetailViewController.swift
> [Feat] 전화 끊은 후에, 모달 띄우기

- Gwayeon/SceneDelegate.swift
#141 
- 상단의 네비바가 두개가 들어가서 메인화면에 여백이 생겼습니다.
- 그래서 지웠습니다!
- 제가 파이어베이스 auth를 연결하는 과정에서 네비바를 하나 더 넣었더라구요 헤헤
> [Fix]: 상단의 네비바 없애기

- Gwayeon/Controllers/EmptyButtonCollectionViewCell.swift
#144 
- 셀의 다른 부분을 눌렀을 때는 아니지만 + 버튼을 눌렀을 때만 윗 공간이 생기던 오류를 해결했습니다
**이전**
**이후**
> [Fix] + 버튼 윗 공간 생기는 에러 수정

- Gwayeon/Controllers/MainTabBarViewController.swift
#146 
TabBarItem image가 못생겨서 변경
TabBarItem title이 Home과 마이로 되어 있는것을 '둘러보기'와 '내 과일'로 변경
수정전
수정후
> [Fix] TabBarItem image 변경 및 TabBarItem title 변경

- Gwayeon/Controllers/DetailViewController.swift
#150 
이미지 뷰와 추천 한 마디 텍스트 위치 조정했습니다.
> [FIX] 이미지 뷰와 추천 한 마디 텍스트 간격 조절

- Gwayeon/Controllers/UserProfileCompletionViewController.swift
#138
온보딩에서 랜덤 과일 선택, 유저데이터에 넣기
> [Feat] 온보딩에서 랜덤 과일 선택, 유저데이터에 넣기

- Gwayeon/Controllers/UserProfileCompletionViewController.swift
#160 
profile 완성 이후 메인화면 들어갈 때 네비게이션바 여백  없애기
수정전
수정후
> [Fix] Hide navigationBar at HomeView

- Gwayeon/Controllers/FriendAddViewController.swift
- Gwayeon/Controllers/FruitRecommend/FruitSelectViewController.swift
- Gwayeon/Controllers/UserProfileCompletionViewController.swift
#162 
- Assets에 있는 이미지 이름이 변경되었는데 코드에는 예전 이름으로 들어가 있어 복숭아 이미지가 나타나지 않았습니다.
- peach-1를 peach로 변경했습니다
> [Fix] 복숭아 이미지명 변경 코드에 적용

- Gwayeon/Manager/FirebaseManager.swift
- Gwayeon/RecommendFarmViewController.swift
#166
- requestFruitInformation 함수 (유저가 과일 등록)
기존에 fruitName: fruitBaseInfo.farmName 으로 되어있어 품종에 농장 이름이 저장됨. fruitName이 데이터에 저장되도록 수정
> [Fix] 새로운 과일 추천 쿼리 수정, 새로운 과일 추천 뷰 버튼 활성화 수정
